# Generated by Django 4.2.16 on 2024-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONFIG_INFO',
            fields=[
                ('create_date', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_category', models.CharField(max_length=100)),
                ('config_name', models.CharField(max_length=100)),
                ('config_value', models.CharField(max_length=100)),
                ('config_remark', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
