# Generated by Django 4.2.16 on 2024-11-16 12:20

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish',
            field=models.ForeignKey(on_delete=models.SET(goods.models.Books.func), to='goods.publish'),
        ),
    ]
