# Generated by Django 4.2.16 on 2024-11-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_books_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.publish'),
        ),
    ]
